Repository EliasDeHondt/K10s, pull requests merged in 2025-03, with the labels that each got.

#100 all alerts replaced with custom one
  App/Frontend/src/app/login/login.component.ts
  App/Frontend/src/app/services/auth.service.ts
  App/Frontend/src/assets/i18n/de.json
  App/Frontend/src/assets/i18n/en.json
  App/Frontend/src/assets/i18n/fr.json
  App/Frontend/src/assets/i18n/nl.json
  App/Frontend/src/assets/i18n/tlh.json
  App/Frontend/src/assets/i18n/zh.json
Labels: In Progress

#101 Reworked concept visualisation
  App/Frontend/src/app/dashboard/dashboard.component.css
  App/Frontend/src/app/dashboard/dashboard.component.ts
  App/Frontend/src/app/services/visualization.service.ts
  App/Frontend/src/app/spider-web/spider-web.component.html
  App/Frontend/src/app/spider-web/spider-web.component.ts
  App/Frontend/src/assets/i18n/de.json
  App/Frontend/src/assets/i18n/en.json
  App/Frontend/src/assets/i18n/fr.json
  App/Frontend/src/assets/i18n/nl.json
  App/Frontend/src/assets/i18n/tlh.json
  App/Frontend/src/assets/i18n/zh.json
Labels: Closed

#102 Cluster visualization backend
  App/Backend/cmd/kubernetes/Client.go
  App/Backend/cmd/kubernetes/Visualization.go
  App/Backend/cmd/kubernetes/handlers/GetVisualization.go
  App/Backend/cmd/main.go
  App/Backend/test.http
Labels: Closed

#105 Add header component with GitHub stars display and remove index CSS
  docs/css/global.css
  docs/css/header.css
  docs/css/index.css
  docs/images/founder1.png
  docs/images/founder2.png
  docs/images/founder3.png
  docs/includes/header.html
  docs/index.html
  docs/js/header.js
  docs/js/main.js
  docs/pages/article1.html
  docs/pages/article2.html
  docs/pptx/presentation.pptx
Labels: Closed, Open

#112 107 task cache visualization in backend
  App/Backend/cmd/kubernetes/Visualization.go
  App/Backend/cmd/kubernetes/VisualizationCache.go
  App/Backend/cmd/kubernetes/handlers/CreateResources.go
  App/Backend/cmd/kubernetes/handlers/GetConfigMaps.go
  App/Backend/cmd/kubernetes/handlers/GetDeployments.go
  App/Backend/cmd/kubernetes/handlers/GetNamespaces.go
  App/Backend/cmd/kubernetes/handlers/GetNodes.go
  App/Backend/cmd/kubernetes/handlers/GetPods.go
  App/Backend/cmd/kubernetes/handlers/GetSecrets.go
  App/Backend/cmd/kubernetes/handlers/GetServices.go
  App/Backend/cmd/kubernetes/handlers/GetStats.go
  App/Backend/cmd/kubernetes/handlers/GetVisualization.go
  App/Backend/cmd/kubernetes/handlers/MetricsSocket.go
  App/Backend/cmd/kubernetes/handlers/util.go
  App/Backend/cmd/main.go
  App/Frontend/package.json
  App/Frontend/src/app/dashboard/dashboard.component.ts
  App/Frontend/src/app/domain/Visualization.ts
  App/Frontend/src/app/services/visualizationWebsocket.service.ts
  App/Frontend/src/app/spider-web/spider-web.component.ts
Labels: Open, Task

#115 114 task namespace filtering in visualization
  App/Backend/cmd/kubernetes/Visualization.go
  App/Backend/cmd/kubernetes/handlers/GetVisualization.go
  App/Backend/cmd/kubernetes/handlers/VisualizationCache.go
  App/Frontend/src/app/dashboard/dashboard.component.css
  App/Frontend/src/app/dashboard/dashboard.component.html
  App/Frontend/src/app/dashboard/dashboard.component.ts
  App/Frontend/src/app/services/visualizationWebsocket.service.ts
  App/Frontend/src/app/spider-web/spider-web.component.ts
Labels: Closed, Task

#117 Bug websocket closing
  App/Backend/cmd/kubernetes/Client.go
  App/Frontend/src/app/services/statWebsocket.service.ts
  App/Frontend/src/app/services/visualizationWebsocket.service.ts
Labels: Open, Bug

#118 Redraw visualization on resolution change
  App/Frontend/src/app/spider-web/spider-web.component.ts
Labels: Open, Bug

#119 Make paging great again!
  App/Frontend/src/app/domain/Kubernetes.ts
  App/Frontend/src/app/search/search.component.html
  App/Frontend/src/app/search/search.component.ts
  App/Frontend/src/app/services/table.service.ts
Labels: Closed, Issue
