Repository EliasDeHondt/K10s, pull requests merged in 2025-02, with the labels that each got.

#53 #51 Enhance index page with GitHub stars display and styling improvem…
  docs/css/index.css
  docs/index.html
  docs/js/main.js
Labels: Open

#66 Settings modal angular
  App/Frontend/src/app/nav/nav.component.css
  App/Frontend/src/app/nav/nav.component.html
  App/Frontend/src/app/nav/nav.component.ts
  App/Frontend/src/styles.css
Labels: Closed

#68 #45 Fix drop down menu TypeScript.
  App/Frontend/src/app/nav/nav.component.css
  App/Frontend/src/app/nav/nav.component.html
  App/Frontend/src/app/nav/nav.component.ts
  App/Frontend/src/app/search/search.component.css
  App/Frontend/src/app/search/search.component.html
  App/Frontend/src/app/search/search.component.ts
Labels: Closed

#75 update ClusterRole permissions to allow create, update, patch, and delete actions
  App/Frontend/src/app/app.config.ts
  App/Frontend/src/app/app.routes.ts
  App/Frontend/src/app/dashboard/dashboard.component.ts
  App/Frontend/src/app/footer/footer.component.ts
  App/Frontend/src/app/login/login.component.ts
  App/Frontend/src/app/nav/nav.component.html
  App/Frontend/src/app/nav/nav.component.ts
  App/Frontend/src/app/notfound/notfound.component.css
  App/Frontend/src/app/notfound/notfound.component.html
  App/Frontend/src/app/notfound/notfound.component.ts
  App/Frontend/src/app/search/search.component.ts
  App/Frontend/src/assets/i18n/de.json
  App/Frontend/src/assets/i18n/en.json
  App/Frontend/src/assets/i18n/fr.json
  App/Frontend/src/assets/i18n/nl.json
  App/Frontend/src/assets/i18n/zh.json
Labels: Closed

#79 Small fixes (Fix radio buttons + smaller French words + chinese words)
  App/Frontend/src/app/search/search.component.css
  App/Frontend/src/app/search/search.component.html
  App/Frontend/src/assets/i18n/fr.json
  App/Frontend/src/assets/i18n/zh.json
Labels: Closed

#78 77 task fronted get total cpu ram and disk usage for the nodes for dashboard page
  App/Backend/cmd/main.go
  App/Backend/go.mod
  App/Backend/go.sum
  App/Frontend/package-lock.json
  App/Frontend/package.json
  App/Frontend/src/app/byte-format.pipe.ts
  App/Frontend/src/app/dashboard/dashboard.component.css
  App/Frontend/src/app/dashboard/dashboard.component.html
  App/Frontend/src/app/dashboard/dashboard.component.ts
  App/Frontend/src/app/services/stats.service.ts
  App/Frontend/src/styles.css
Labels: In Progress

#85 82 task implement load iconskeletons
  App/Frontend/src/app/dashboard/dashboard.component.css
  App/Frontend/src/app/dashboard/dashboard.component.html
  App/Frontend/src/app/dashboard/dashboard.component.ts
  App/Frontend/src/app/loading/loading.component.css
  App/Frontend/src/app/loading/loading.component.html
  App/Frontend/src/app/loading/loading.component.ts
  App/Frontend/src/app/search/search.component.css
  App/Frontend/src/app/search/search.component.html
  App/Frontend/src/app/search/search.component.ts
Labels: In Progress

#87 86 task frontend small fixes/extras
  App/Frontend/src/app/add/add.component.css
  App/Frontend/src/app/add/add.component.html
  App/Frontend/src/app/dashboard/dashboard.component.css
  App/Frontend/src/app/dashboard/dashboard.component.html
  App/Frontend/src/app/dashboard/dashboard.component.ts
  App/Frontend/src/app/search/search.component.css
  App/Frontend/src/app/search/search.component.html
  App/Frontend/src/styles.css
Labels: Closed

#84 Deployment through app
  App/Backend/cmd/kubernetes/Client.go
  App/Backend/cmd/kubernetes/Namespace.go
  App/Backend/cmd/kubernetes/Node.go
  App/Backend/cmd/kubernetes/Pod.go
  App/Backend/cmd/kubernetes/Setup.go
  App/Backend/cmd/kubernetes/handlers/Deploy.go
  App/Backend/cmd/kubernetes/handlers/GetConfigMaps.go
  App/Backend/cmd/kubernetes/handlers/GetDeployments.go
  App/Backend/cmd/kubernetes/handlers/GetNodes.go
  App/Backend/cmd/kubernetes/handlers/GetPods.go
  App/Backend/cmd/kubernetes/handlers/GetSecrets.go
  App/Backend/cmd/kubernetes/handlers/GetServices.go
  App/Backend/cmd/kubernetes/handlers/GetStats.go
  App/Backend/cmd/main.go
  App/Backend/test.http
  App/Backend/testing/create_handler_test.go
  App/Backend/testing/get_handler_test.go
  App/Backend/testing/test_yamls/Combined.yaml
  App/Backend/testing/test_yamls/ConfigMap.yaml
  App/Backend/testing/test_yamls/Deployment.yaml
  App/Backend/testing/test_yamls/Namespace.yaml
  App/Backend/testing/test_yamls/Node.yaml
  App/Backend/testing/test_yamls/Pod.yaml
  App/Backend/testing/test_yamls/Secret.yaml
  App/Backend/testing/test_yamls/Service.yaml
Labels: Closed

#76 72 task investigate cluster visualizations
  App/Frontend/package-lock.json
  App/Frontend/package.json
  App/Frontend/src/app/app.routes.ts
  App/Frontend/src/app/dashboard/dashboard.component.css
  App/Frontend/src/app/dashboard/dashboard.component.html
  App/Frontend/src/app/dashboard/dashboard.component.ts
  App/Frontend/src/app/spider-web/spider-web.component.css
  App/Frontend/src/app/spider-web/spider-web.component.html
  App/Frontend/src/app/spider-web/spider-web.component.ts
Labels: Closed

#89 Add Klingon (tlh) Translation to the Application.
  App/Frontend/src/app/dashboard/dashboard.component.css
  App/Frontend/src/app/nav/nav.component.ts
  App/Frontend/src/assets/i18n/tlh.json
Labels: Closed

#91 Connect frontend to backend
  App/Backend/cmd/auth/AuthHandlers.go
  App/Backend/cmd/kubernetes/handlers/CreateResources.go
  App/Backend/cmd/main.go
  App/Frontend/angular.json
  App/Frontend/src/app/app.routes.ts
  App/Frontend/src/app/authGuard/auth.guard.ts
  App/Frontend/src/app/dashboard/dashboard.component.ts
  App/Frontend/src/app/domain/Kubernetes.ts
  App/Frontend/src/app/domain/Metrics.ts
  App/Frontend/src/app/login/login.component.ts
  App/Frontend/src/app/nav/nav.component.html
  App/Frontend/src/app/nav/nav.component.ts
  App/Frontend/src/app/pipes/config-map-cast.pipe.ts
  App/Frontend/src/app/pipes/deployment-cast.pipe.ts
  App/Frontend/src/app/pipes/node-cast.pipe.ts
  App/Frontend/src/app/pipes/pod-cast.pipe.ts
  App/Frontend/src/app/pipes/secret-cast.pipe.ts
  App/Frontend/src/app/pipes/service-cast.pipe.ts
  App/Frontend/src/app/search-table/config-map-table/config-map-table.component.css
  App/Frontend/src/app/search-table/config-map-table/config-map-table.component.html
  App/Frontend/src/app/search-table/config-map-table/config-map-table.component.ts
  App/Frontend/src/app/search-table/deployment-table/deployment-table.component.css
  App/Frontend/src/app/search-table/deployment-table/deployment-table.component.html
  App/Frontend/src/app/search-table/deployment-table/deployment-table.component.ts
  App/Frontend/src/app/search-table/node-table/node-table.component.css
  App/Frontend/src/app/search-table/node-table/node-table.component.html
  App/Frontend/src/app/search-table/node-table/node-table.component.ts
  App/Frontend/src/app/search-table/pod-table/pod-table.component.css
  App/Frontend/src/app/search-table/pod-table/pod-table.component.html
  App/Frontend/src/app/search-table/pod-table/pod-table.component.ts
  App/Frontend/src/app/search-table/secret-table/secret-table.component.css
  App/Frontend/src/app/search-table/secret-table/secret-table.component.html
  App/Frontend/src/app/search-table/secret-table/secret-table.component.ts
  App/Frontend/src/app/search-table/service-table/service-table.component.css
  App/Frontend/src/app/search-table/service-table/service-table.component.html
  App/Frontend/src/app/search-table/service-table/service-table.component.ts
  App/Frontend/src/app/search/search.component.html
  App/Frontend/src/app/search/search.component.ts
  App/Frontend/src/app/services/add.service.ts
  App/Frontend/src/app/services/auth.service.ts
  App/Frontend/src/app/services/stats.service.ts
  App/Frontend/src/app/services/table.service.ts
  App/Frontend/src/app/util/cookies.ts
  App/Frontend/src/assets/i18n/de.json
  App/Frontend/src/assets/i18n/en.json
  App/Frontend/src/assets/i18n/fr.json
  App/Frontend/src/assets/i18n/nl.json
  App/Frontend/src/assets/i18n/zh.json
  App/Frontend/src/environments/environment.development.ts
  App/Frontend/src/environments/environment.ts
Labels: Closed

#93 92 task backend and frontend image communication issue in kubernetes
  App/Backend/Dockerfile
  App/Frontend/Dockerfile
  App/Frontend/default.conf
  App/Frontend/src/app/spider-web/spider-web.component.css
  App/Frontend/src/app/spider-web/spider-web.component.html
  App/Frontend/src/app/spider-web/spider-web.component.ts
  App/Frontend/src/assets/i18n/de.json
  App/Frontend/src/assets/i18n/en.json
  App/Frontend/src/assets/i18n/fr.json
  App/Frontend/src/assets/i18n/nl.json
  App/Frontend/src/assets/i18n/tlh.json
  App/Frontend/src/assets/i18n/zh.json
  App/Frontend/src/environments/environment.production.ts
  App/Frontend/src/main.ts
  Kubernetes/k10s.yaml
  README.md
Labels: In Progress

#95 #43 filter functionality
  App/Backend/cmd/kubernetes/Client.go
  App/Backend/cmd/kubernetes/Pod.go
  App/Backend/cmd/kubernetes/Setup.go
  App/Backend/cmd/kubernetes/handlers/GetConfigMaps.go
  App/Backend/cmd/kubernetes/handlers/GetDeployments.go
  App/Backend/cmd/kubernetes/handlers/GetNamespaces.go
  App/Backend/cmd/kubernetes/handlers/GetNodes.go
  App/Backend/cmd/kubernetes/handlers/GetPods.go
  App/Backend/cmd/kubernetes/handlers/GetSecrets.go
  App/Backend/cmd/kubernetes/handlers/GetServices.go
  App/Backend/cmd/main.go
  App/Backend/testing/get_handler_test.go
  App/Frontend/src/app/domain/Kubernetes.ts
  App/Frontend/src/app/search/search.component.html
  App/Frontend/src/app/search/search.component.ts
  App/Frontend/src/app/services/filterdata.service.ts
  App/Frontend/src/app/services/table.service.ts
Labels: In Progress

#96 Websockets
  App/Backend/cmd/kubernetes/handlers/MetricsSocket.go
  App/Backend/cmd/main.go
  App/Backend/go.mod
  App/Backend/go.sum
  App/Frontend/src/app/dashboard/dashboard.component.html
  App/Frontend/src/app/dashboard/dashboard.component.ts
  App/Frontend/src/app/services/statWebsocket.service.ts
  App/Frontend/src/app/services/stats.service.ts
Labels: Closed

#97 Refactor dashboard component: improve button styles and add download …
  App/Frontend/src/app/dashboard/dashboard.component.css
  App/Frontend/src/app/dashboard/dashboard.component.html
Labels: In Progress
